services:
  - type: web
    name: vigil-pay
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: vigil-pay.onrender.com
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: DATABASE_URL
        fromDatabase:
          name: vigil-pay-db
          property: connectionString

  - type: postgresql
    name: vigil-pay-db
    plan: free
    ipAllowList: []